version: '3.4'
services:
  hab:
    image: jacobalberty/unifi:5.9
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './data:/unifi'
    network_mode: host
    environment:
      RUNAS_UID0: 'false'
